"use client"

import { motion, useReducedMotion } from "framer-motion"
import { ArrowRight, Check } from "lucide-react"
import { cn } from "@/lib/utils"
import { LandingSectionHeader } from "../section-shell"

/* ===================================================================
   Data view of the landing page — rendered when the hero's audience
   toggle is on "Data". The pitch: synthetic, long-horizon, multimodal
   trajectories generated by Coasty's own agent fleet on real operating
   systems, customizable down to the schema, delivered in under 30
   days. Each section carries exactly one quiet visualization (a step
   density strip, an alignment grid, a delivery-artifact row, a spec
   card, a 30-day timeline) — all deterministic, SSR-safe, and built
   from hairlines and the foreground scale, no decorative color.
   English-only by design, matching the other non-product views.
   Claims describe the real generation pipeline; no invented volume
   stats, client names, benchmarks results, or certifications.
   =================================================================== */

const EASE: [number, number, number, number] = [0.22, 1, 0.36, 1]

// Shared whileInView reveal, same once-only viewport pattern as the
// sibling sections (no isMobile-conditional motion props).
const reveal = (delay = 0) => ({
  initial: { opacity: 0, y: 16 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: "-80px" },
  transition: { duration: 0.5, delay, ease: EASE },
})

/* ─── Visualization 1: step-density strip ───
 * One long task rendered as a waveform of per-step activity. Heights are
 * a deterministic function of the index (no randomness — SSR and client
 * must paint identically). Taller, darker bars mark application switches;
 * the amber span is an error plus the recovery that followed; the strip
 * ends in a verified outcome.
 * Micro animation: the bars sweep up left to right once on first view (a
 * task playing out), then the caption settles in. Transform/opacity only;
 * reduced motion snaps everything (zero durations). */
const STRIP_BARS = 96
const APP_SWITCHES = new Set([0, 26, 54, 82])
const RECOVERY = { from: 60, to: 66 }

function TrajectoryStrip() {
  const reduced = useReducedMotion()
  return (
    <div className="mb-12">
      <motion.div
        aria-hidden="true"
        initial="hidden"
        whileInView="show"
        viewport={{ once: true, margin: "-60px" }}
        className="flex items-end gap-[2px] h-[44px]"
      >
        {Array.from({ length: STRIP_BARS }, (_, i) => {
          const h = APP_SWITCHES.has(i)
            ? 44
            : 12 + Math.abs(Math.sin(i * 0.83) + Math.sin(i * 0.29)) * 11
          const recovering = i >= RECOVERY.from && i <= RECOVERY.to
          return (
            <motion.div
              key={i}
              custom={i}
              variants={{
                hidden: { scaleY: 0, opacity: 0 },
                show: (idx: number) => ({
                  scaleY: 1,
                  opacity: 1,
                  transition: reduced
                    ? { duration: 0 }
                    : { delay: idx * 0.008, duration: 0.4, ease: EASE },
                }),
              }}
              style={{ height: `${Math.round(h)}px`, transformOrigin: "bottom" }}
              className={cn(
                "flex-1 rounded-t-[1px]",
                recovering
                  ? "bg-amber-500/45"
                  : APP_SWITCHES.has(i)
                    ? "bg-foreground/45"
                    : "bg-foreground/[0.16]",
              )}
            />
          )
        })}
      </motion.div>
      <motion.div
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true, margin: "-60px" }}
        transition={reduced ? { duration: 0 } : { delay: 0.55, duration: 0.5, ease: EASE }}
        className="mt-2.5 flex items-baseline justify-between gap-4 border-t border-foreground/[0.07] pt-2.5"
      >
        <span className="min-w-0 truncate font-mono text-[10px] tracking-[0.14em] uppercase text-muted-foreground/55">
          browser · terminal · spreadsheet · email
        </span>
        <span className="flex shrink-0 items-center gap-3 font-mono text-[10px] tracking-[0.14em] uppercase text-muted-foreground/55">
          <span className="text-amber-600/70 dark:text-amber-400/70">recovery</span>
          <span className="inline-flex items-center gap-1 text-emerald-600/80 dark:text-emerald-400/80">
            <Check className="h-3 w-3" />
            verified
          </span>
        </span>
      </motion.div>
    </div>
  )
}

/* ─── Visualization 2: modality alignment grid ───
 * Four modality lanes across nine steps, with one step column lifted to
 * show that every modality is captured against the same timestamp.
 * Micro animation: cells cascade in column by column (steps accumulating),
 * each lane trailing slightly; the aligned column and caption land last. */
const LANES = ["vision", "action", "ui state", "outcome"] as const
const GRID_COLS = 9
const ALIGNED_COL = 5

function ModalityGrid() {
  const reduced = useReducedMotion()
  const cellDelay = (lane: number, col: number) => col * 0.05 + lane * 0.07
  return (
    <motion.div
      initial="hidden"
      whileInView="show"
      viewport={{ once: true, margin: "-60px" }}
      className="mb-12"
    >
      <div className="space-y-1.5">
        {LANES.map((lane, laneIdx) => (
          <div key={lane} className="flex items-center gap-3">
            <motion.span
              variants={{
                hidden: { opacity: 0 },
                show: {
                  opacity: 1,
                  transition: reduced
                    ? { duration: 0 }
                    : { delay: laneIdx * 0.07, duration: 0.4, ease: EASE },
                },
              }}
              className="w-[64px] shrink-0 text-right font-mono text-[9.5px] tracking-[0.14em] uppercase text-muted-foreground/55"
            >
              {lane}
            </motion.span>
            <div aria-hidden="true" className="flex flex-1 gap-1.5">
              {Array.from({ length: GRID_COLS }, (_, i) => (
                <motion.div
                  key={i}
                  variants={{
                    hidden: { opacity: 0, scale: 0.5 },
                    show: {
                      opacity: 1,
                      scale: 1,
                      transition: reduced
                        ? { duration: 0 }
                        : { delay: cellDelay(laneIdx, i), duration: 0.35, ease: EASE },
                    },
                  }}
                  className={cn(
                    "h-3 flex-1 rounded-[3px]",
                    i === ALIGNED_COL ? "bg-foreground/40" : "bg-foreground/[0.07]",
                  )}
                />
              ))}
            </div>
          </div>
        ))}
      </div>
      <motion.div
        variants={{
          hidden: { opacity: 0 },
          show: {
            opacity: 1,
            transition: reduced ? { duration: 0 } : { delay: 0.65, duration: 0.5, ease: EASE },
          },
        }}
      >
        <div className="mt-2.5 flex items-center gap-3">
          <span className="w-[64px] shrink-0" />
          <div className="flex flex-1 gap-1.5">
            {Array.from({ length: GRID_COLS }, (_, i) => (
              <span
                key={i}
                className={cn(
                  "flex-1 text-center font-mono text-[9px]",
                  i === ALIGNED_COL ? "text-foreground/70" : "text-muted-foreground/35",
                )}
              >
                {i === ALIGNED_COL ? "t₄₆" : "·"}
              </span>
            ))}
          </div>
        </div>
        <p className="mt-3 text-center font-mono text-[10px] tracking-[0.14em] uppercase text-muted-foreground/55">
          one aligned tuple per step
        </p>
      </motion.div>
    </motion.div>
  )
}

/* ─── Visualization 3: delivery artifacts ───
 * What actually lands with every batch — diligence made tangible. */
const ARTIFACTS = [
  { file: "datasheet.md", desc: "Methodology, coverage, limits" },
  { file: "qa-report.json", desc: "Verification rates per batch" },
  { file: "decontamination.txt", desc: "Screened suites, match logs" },
  { file: "verifiers/", desc: "Reusable reward functions" },
] as const

function ArtifactRow() {
  const reduced = useReducedMotion()
  return (
    <motion.div
      initial="hidden"
      whileInView="show"
      viewport={{ once: true, margin: "-60px" }}
      className="mb-12 grid grid-cols-2 gap-2 lg:grid-cols-4"
    >
      {ARTIFACTS.map((a, i) => (
        <motion.div
          key={a.file}
          variants={{
            hidden: { opacity: 0, y: 10 },
            show: {
              opacity: 1,
              y: 0,
              transition: reduced
                ? { duration: 0 }
                : { delay: i * 0.08, duration: 0.45, ease: EASE },
            },
          }}
          className="rounded-xl border border-foreground/[0.08] px-3.5 py-3"
        >
          <div className="font-mono text-[11px] text-foreground/80 truncate">{a.file}</div>
          <div className="mt-1 text-[11px] leading-[1.45] text-muted-foreground/55">
            {a.desc}
          </div>
        </motion.div>
      ))}
    </motion.div>
  )
}

/* ─── Visualization 4: the dataset spec card ───
 * Customizability made concrete: the distribution is a config you write. */
const SPEC_LINES = [
  ["horizon", "p50 120 · p95 400 steps"],
  ["os_mix", "linux 55 / windows 35 / macos 10"],
  ["apps", "erp · browser · sheets · email"],
  ["noise", "popups on · latency jitter on"],
  ["annotations", "rationales + subgoals"],
  ["format", "parquet + webdataset"],
  ["refresh", "weekly"],
  ["splits", "train 90 / val 5 / test 5"],
] as const

function SpecCard() {
  const reduced = useReducedMotion()
  return (
    <motion.div
      initial="hidden"
      whileInView="show"
      viewport={{ once: true, margin: "-60px" }}
      className="mx-auto mb-12 max-w-[560px]"
    >
      <motion.div
        variants={{
          hidden: { opacity: 0 },
          show: {
            opacity: 1,
            transition: reduced ? { duration: 0 } : { duration: 0.45, ease: EASE },
          },
        }}
        className="overflow-hidden rounded-2xl border border-foreground/[0.08] bg-background/60"
      >
        <div className="flex items-center justify-between border-b border-foreground/[0.06] px-4 py-2.5">
          <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground/60">
            dataset.spec
          </span>
          <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground/40">
            yours to define
          </span>
        </div>
        {/* Lines settle one after another, a spec being written down. */}
        <div className="px-4 py-4 font-mono text-[11px] sm:text-[12px] leading-[1.9]">
          {SPEC_LINES.map(([k, v], i) => (
            <motion.div
              key={k}
              variants={{
                hidden: { opacity: 0 },
                show: {
                  opacity: 1,
                  transition: reduced
                    ? { duration: 0 }
                    : { delay: 0.15 + i * 0.07, duration: 0.35, ease: EASE },
                },
              }}
              className="flex gap-3"
            >
              <span className="w-[104px] shrink-0 text-muted-foreground/45">{k}</span>
              <span className="text-muted-foreground truncate">{v}</span>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </motion.div>
  )
}

/* ─── Visualization 5: the 30-day timeline ───
 * Spec to delivered, one month, QA gates at each phase boundary. */
const PHASES = [
  { label: "Spec", days: "Days 1-3", grow: 3 },
  { label: "Pilot", days: "Days 4-10", grow: 7 },
  { label: "Scale", days: "Days 11-30", grow: 20 },
] as const

function ThirtyDayBar() {
  const reduced = useReducedMotion()
  // Each segment starts growing as the previous one finishes, so the month
  // plays out left to right; the verified check pops once the bar lands.
  const SEGMENT_STARTS = [0, 0.3, 0.62] as const
  return (
    <motion.div
      initial="hidden"
      whileInView="show"
      viewport={{ once: true, margin: "-60px" }}
      className="mb-12"
    >
      {/* The bar row and the label row share the same flexGrow values and the
          same fixed-width trailing block, so labels sit exactly under their
          segments at every viewport width. */}
      <div aria-hidden="true" className="flex items-center gap-1">
        {PHASES.map((p, i) => (
          <motion.div
            key={p.label}
            variants={{
              hidden: { scaleX: 0, opacity: 0 },
              show: {
                scaleX: 1,
                opacity: 1,
                transition: reduced
                  ? { duration: 0 }
                  : { delay: SEGMENT_STARTS[i], duration: 0.45, ease: EASE },
              },
            }}
            style={{ flexGrow: p.grow, transformOrigin: "left" }}
            className={cn(
              "h-1.5 min-w-0 basis-0 rounded-full",
              i === 0 && "bg-foreground/[0.15]",
              i === 1 && "bg-foreground/[0.3]",
              i === 2 && "bg-foreground/[0.5]",
            )}
          />
        ))}
        <span className="ml-1.5 flex w-[56px] shrink-0 justify-end">
          <motion.span
            variants={{
              hidden: { scale: 0, opacity: 0 },
              show: {
                scale: 1,
                opacity: 1,
                transition: reduced
                  ? { duration: 0 }
                  : { delay: 1.05, type: "spring", stiffness: 420, damping: 22 },
              },
            }}
            className="grid h-5 w-5 place-items-center rounded-full bg-emerald-500/15"
          >
            <Check className="h-3 w-3 text-emerald-600 dark:text-emerald-400" />
          </motion.span>
        </span>
      </div>
      <motion.div
        variants={{
          hidden: { opacity: 0 },
          show: {
            opacity: 1,
            transition: reduced ? { duration: 0 } : { delay: 0.9, duration: 0.5, ease: EASE },
          },
        }}
        className="mt-2.5 flex items-baseline gap-1"
      >
        {PHASES.map((p) => (
          <div key={p.label} style={{ flexGrow: p.grow }} className="min-w-0 basis-0">
            <div className="font-mono text-[10px] tracking-[0.12em] uppercase text-muted-foreground/65 truncate">
              {p.label}
            </div>
            <div className="font-mono text-[9.5px] text-muted-foreground/40 truncate">
              {p.days}
            </div>
          </div>
        ))}
        <div className="ml-1.5 w-[56px] shrink-0 text-right">
          <div className="font-mono text-[10px] tracking-[0.12em] uppercase text-foreground/70">
            Day 30
          </div>
          <div className="font-mono text-[9.5px] text-muted-foreground/40">delivered</div>
        </div>
      </motion.div>
    </motion.div>
  )
}

/* ─── Why this data wins ─── */

const WHY_POINTS = [
  {
    title: "Generated on real computers",
    body: "Every trajectory runs on a real operating system with real applications, browsers, files, and failure modes, not a scripted simulator. The distribution your model meets in production is the one it trains on.",
  },
  {
    title: "Long-horizon by construction",
    body: "Tasks span tens to hundreds of steps across multiple applications, with sub-goals, interruptions, and context carried forward. This is the regime where agent training data is scarcest and where ours is densest.",
  },
  {
    title: "Multimodal at every step",
    body: "Each step pairs the screenshot with the structured action taken, exact cursor coordinates, and the UI state beneath it. Vision, action, and outcome stay aligned frame by frame, with nothing stitched together after the fact.",
  },
  {
    title: "Error recovery included",
    body: "Real runs hit dead ends, surprise dialogs, and slow pages, and the data keeps the correction that followed. Models learn to recover because the trajectories contain recoveries, not just clean demonstrations.",
  },
  {
    title: "Verified outcomes, RL-ready",
    body: "Every task ships with an initial-state setup and an execution-based success check: file diffs, terminal output, on-screen state. A demonstration with a verifier is reusable forever, for SFT, rejection sampling, rollouts, and process rewards.",
  },
  {
    title: "Fresh and contamination-aware",
    body: "Data is generated on demand against current software versions, and we screen task families against public evaluation suites so your benchmark numbers measure your model, not a leak.",
  },
] as const

export function DataWhySection({ isMobile }: { isMobile: boolean }) {
  return (
    <section id="data-why" className="relative py-20 sm:py-24 lg:py-32 px-8 sm:px-10 lg:px-12 scroll-mt-24">
      <div className="mx-auto max-w-5xl">
        <LandingSectionHeader
          isMobile={isMobile}
          title="Why this data is different"
          subtitle="One task, hundreds of steps, four applications, one verified outcome. That shape is the product."
        />

        <TrajectoryStrip />

        <motion.div
          {...reveal(0.08)}
          className="grid overflow-hidden rounded-2xl border border-foreground/[0.08] bg-foreground/[0.06] gap-px sm:grid-cols-2 lg:grid-cols-3"
        >
          {WHY_POINTS.map((p) => (
            <div key={p.title} className="bg-background p-6 sm:p-7">
              <h3 className="text-[15px] font-medium tracking-[-0.01em] text-foreground">
                {p.title}
              </h3>
              <p className="mt-2.5 text-[13px] leading-[1.65] text-muted-foreground/70">
                {p.body}
              </p>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}

/* ─── What is inside a trajectory ─── */

const SPEC_ROWS = [
  {
    modality: "Screenshots",
    detail: "Full-resolution captures at every step, before and after each action, with timing metadata.",
  },
  {
    modality: "Structured actions",
    detail: "Typed JSON in a documented, pyautogui-style action space with exact coordinates, plus raw input events so you can re-map everything to your own schema losslessly.",
  },
  {
    modality: "UI state",
    detail: "DOM snapshots and clickable-element maps for browser steps; window and application context on the desktop.",
  },
  {
    modality: "Terminal and files",
    detail: "Command transcripts, outputs, and file diffs whenever the task touches the shell or the filesystem.",
  },
  {
    modality: "Task metadata",
    detail: "The natural-language goal, sub-task decomposition, horizon length, app inventory, and environment manifest.",
  },
  {
    modality: "Outcome labels",
    detail: "Programmatic success checks per trajectory, plus a failure taxonomy on unsuccessful runs for hard-negative mining.",
  },
  {
    modality: "Verifiers",
    detail: "The initial-state config and execution-based checker for each task, so you can rerun, audit, and reuse every task as an RL reward function.",
  },
] as const

export function DataSpecSection({ isMobile }: { isMobile: boolean }) {
  return (
    <section id="data-spec" className="relative py-20 sm:py-24 lg:py-32 px-8 sm:px-10 lg:px-12 scroll-mt-24">
      <div className="mx-auto max-w-3xl">
        <LandingSectionHeader
          isMobile={isMobile}
          title="What is inside every trajectory"
          subtitle="One record per step. Every modality aligned to the same timestamp, so nothing has to be reconciled downstream."
        />

        <ModalityGrid />

        <motion.div
          {...reveal(0.08)}
          className="overflow-hidden rounded-2xl border border-foreground/[0.08]"
        >
          <div className="divide-y divide-foreground/[0.06]">
            {SPEC_ROWS.map((r) => (
              <div
                key={r.modality}
                className={cn(
                  "grid gap-1 px-5 sm:px-6 sm:grid-cols-[180px_1fr] sm:gap-6",
                  isMobile ? "py-4" : "py-4.5",
                )}
              >
                <div className="font-mono text-[11px] uppercase tracking-[0.14em] text-muted-foreground/60 sm:pt-0.5">
                  {r.modality}
                </div>
                <p className="text-[13px] leading-[1.6] text-muted-foreground/75">{r.detail}</p>
              </div>
            ))}
          </div>
        </motion.div>

        <motion.p
          {...reveal(0.1)}
          className="mt-5 text-center text-[12px] leading-[1.6] text-muted-foreground/55"
        >
          Delivered as JSONL plus media archives by default, or in any schema you specify:
          Parquet, WebDataset, or your internal format.
        </motion.p>
      </div>
    </section>
  )
}

/* ─── What serious buyers evaluate ─── */

const BUYER_POINTS = [
  {
    title: "Provenance and licensing",
    body: "Every record is generated by our own agents on our own infrastructure, with generator lineage documented per batch. You get a clean chain of custody, explicit rights to train, fine-tune, and evaluate, and no scraped or encumbered sources anywhere in the pipeline.",
  },
  {
    title: "Privacy by construction",
    body: "The pipeline is synthetic end to end. Tasks run in isolated virtual machines against synthetic accounts, documents, and inboxes, so no human PII ever enters a trajectory. There is nothing to redact, nothing to get consent for, and nothing to leak.",
  },
  {
    title: "Quality you can audit",
    body: "Acceptance criteria are fixed in numbers before generation starts. Every delivery ships with per-batch QA reports, programmatic verification rates, and audit samples, and batches that miss the bar are regenerated at our cost, not yours.",
  },
  {
    title: "Benchmark hygiene",
    body: "Task families are screened against the public computer-use suites your evals depend on, OSWorld, WebArena, ScreenSpot, and Mind2Web among them, and a decontamination report ships with every delivery. Held-out splits follow your protocol.",
  },
  {
    title: "Scale without renegotiation",
    body: "Generation scales with compute, not headcount. The pilot pipeline and the production pipeline are the same system, so growing from thousands to millions of steps is a parameter change, not a new contract.",
  },
  {
    title: "Governance-ready delivery",
    body: "Each dataset ships with a datasheet: methodology, environment manifest, distribution and diversity statistics, known limitations, and refresh cadence, structured to map onto the EU AI Act training-data summary. Encrypted handoff, retention windows you set, and verified deletion at contract end.",
  },
] as const

export function DataBuyersSection({ isMobile }: { isMobile: boolean }) {
  return (
    <section id="data-buyers" className="relative py-20 sm:py-24 lg:py-32 px-8 sm:px-10 lg:px-12 scroll-mt-24">
      <div className="mx-auto max-w-5xl">
        <LandingSectionHeader
          isMobile={isMobile}
          title="Built for how serious buyers evaluate data"
          subtitle="The questions large AI organizations ask in diligence are the ones this pipeline was designed to answer. This is what lands with every batch:"
        />

        <ArtifactRow />

        <motion.div
          {...reveal(0.08)}
          className="grid overflow-hidden rounded-2xl border border-foreground/[0.08] bg-foreground/[0.06] gap-px sm:grid-cols-2 lg:grid-cols-3"
        >
          {BUYER_POINTS.map((p) => (
            <div key={p.title} className="bg-background p-6 sm:p-7">
              <h3 className="text-[15px] font-medium tracking-[-0.01em] text-foreground">
                {p.title}
              </h3>
              <p className="mt-2.5 text-[13px] leading-[1.65] text-muted-foreground/70">
                {p.body}
              </p>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}

/* ─── Customizability ─── */

const CUSTOM_LEVERS = [
  {
    lever: "Task taxonomy",
    detail: "Define the task families that matter to you: ERP workflows, browser research, spreadsheet operations, IT administration, customer support flows, or your own product end to end.",
  },
  {
    lever: "Environment mix",
    detail: "Choose operating systems, browsers, screen resolutions, locales, and application versions. We build the fleet to match your target distribution.",
  },
  {
    lever: "Horizon profile",
    detail: "Set the distribution of trajectory lengths, from ten-step errands to multi-hundred-step projects, including how often tasks should be interrupted and resumed.",
  },
  {
    lever: "Difficulty and noise",
    detail: "Dial in pop-ups, latency, ambiguous instructions, stale UI, and adversarial layouts to harden your model against the real world.",
  },
  {
    lever: "Annotation density",
    detail: "From lean action-only traces to step-level rationales, sub-goal labels, and per-step state summaries, depending on what your training objective needs.",
  },
  {
    lever: "Schema and format",
    detail: "Your field names, your coordinate convention, your packaging. JSONL, Parquet, WebDataset, or a custom spec, with media layout to match your loaders.",
  },
  {
    lever: "Delivery cadence",
    detail: "A one-time corpus, scheduled refreshes against current software, or live generation through the same API that runs our production agents.",
  },
  {
    lever: "Splits and exclusivity",
    detail: "Train, validation, and test splits built to your protocol, with exclusive task families reserved for your organization when required. We are independent, so your roadmap stays your own.",
  },
] as const

export function DataCustomSection({ isMobile }: { isMobile: boolean }) {
  return (
    <section id="data-custom" className="relative py-20 sm:py-24 lg:py-32 px-8 sm:px-10 lg:px-12 scroll-mt-24">
      <div className="mx-auto max-w-4xl">
        <LandingSectionHeader
          isMobile={isMobile}
          title="Customizable down to the schema"
          subtitle="You are not buying a fixed corpus. You are writing a spec, and the pipeline generates to it."
        />

        <SpecCard />

        <motion.div
          {...reveal(0.08)}
          className="grid overflow-hidden rounded-2xl border border-foreground/[0.08] bg-foreground/[0.06] gap-px sm:grid-cols-2"
        >
          {CUSTOM_LEVERS.map((l) => (
            <div key={l.lever} className="bg-background p-6 sm:p-7">
              <h3 className="text-[14.5px] font-medium tracking-[-0.01em] text-foreground">
                {l.lever}
              </h3>
              <p className="mt-2 text-[13px] leading-[1.6] text-muted-foreground/70">
                {l.detail}
              </p>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}

/* ─── The 30-day path to production ─── */

const PROCESS_STEPS = [
  {
    step: "DAYS 1-3",
    title: "Spec",
    body: "A working session to define your task taxonomy, environment mix, schema, and the acceptance criteria a batch must pass. You leave with a written dataset spec.",
  },
  {
    step: "DAYS 4-10",
    title: "Pilot",
    body: "A sample dataset generated against the spec, sized for a real training or evaluation run. You validate it with your own pipeline, and we revise the spec once, free.",
  },
  {
    step: "DAYS 11-30",
    title: "Scale",
    body: "Production generation in weekly drops, each gated by per-batch QA reports and verification rates. Full delivery lands by day 30, with refresh cadence if you want it.",
  },
] as const

export function DataProcessSection({ isMobile }: { isMobile: boolean }) {
  return (
    <section id="data-process" className="relative py-20 sm:py-24 lg:py-32 px-8 sm:px-10 lg:px-12 scroll-mt-24">
      <div className="mx-auto max-w-4xl">
        <LandingSectionHeader
          isMobile={isMobile}
          title="The highest quality, in under 30 days"
          subtitle="Quality here is a pipeline property, not a promise. Verification is programmatic and generation runs on the same fleet as our production agents, so the calendar is short because nothing is manual."
        />

        <ThirtyDayBar />

        <motion.div
          {...reveal(0.08)}
          className="grid overflow-hidden rounded-2xl border border-foreground/[0.08] bg-foreground/[0.06] gap-px sm:grid-cols-3"
        >
          {PROCESS_STEPS.map((s) => (
            <div key={s.step} className="bg-background p-6 sm:p-7">
              <div className="font-mono text-[10px] tracking-[0.2em] text-muted-foreground/50">
                {s.step}
              </div>
              <h3 className="mt-3 text-[15px] font-medium tracking-[-0.01em] text-foreground">
                {s.title}
              </h3>
              <p className="mt-2 text-[13px] leading-[1.6] text-muted-foreground/70">{s.body}</p>
            </div>
          ))}
        </motion.div>

        <motion.div {...reveal(0.12)} className="mt-10 flex flex-col items-center gap-3">
          <a
            href="https://cal.com/coasty/coasty-data-call"
            target="_blank"
            rel="noopener noreferrer"
            className="group inline-flex items-center justify-center gap-2 rounded-full bg-foreground px-6 py-2.5 text-[13.5px] font-medium text-background transition-transform duration-200 hover:opacity-90 active:scale-[0.98]"
          >
            Book a data call
            <ArrowRight className="h-3.5 w-3.5 transition-transform duration-200 group-hover:translate-x-0.5" />
          </a>
          <p className="text-[12px] text-muted-foreground/55">
            Sample datasets are available under NDA.
          </p>
        </motion.div>
      </div>
    </section>
  )
}
